Resources:
  CodeBuild:
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Name: ${self:service.name}
      Description: This is the codebuild project for the ${env:APP_NAME}
      ServiceRole:
        Fn::GetAtt:
          - WebsiteRole
          - Arn
      Artifacts:
        Type: CODEPIPELINE
        Name: ${self:service.name}-build
        Packaging: NONE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:4.0'
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: ${env:GITHUB_TOKEN}
          - Name: GITHUB_OWNER
            Value: ${env:GITHUB_OWNER}
          - Name: GITHUB_REPO
            Value: ${env:GITHUB_REPO}
          - Name: NODE_ENV
            Value: ${env:NODE_ENV}
          - Name: REGION
            Value: ${env:REGION}
          - Name: AWS_ACCESS_KEY_ID
            Value: ${env:AWS_ACCESS_KEY_ID}
          - Name: AWS_SECRET_ACCESS_KEY
            Value: ${env:AWS_SECRET_ACCESS_KEY}
          - Name: RUN_LOCAL
            Value: true
      Source:
        Type: CODEPIPELINE
